title: <p align="center"> Derek Bonilla </p>

logo: "/images/logo.png?raw=true" 

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/derekbonilla/">LinkedIn</a> |
  <a href="https://github.com/derekbonilla">GitHub</a>
  </p>

  <p align="justify">
  I am an aspiring Data Analyst and recently the Google Data Analytics Certificate program.
  <br><br>
  I work as a Resource Specialist at Unite Us with a focus on supporting the development of community networks and managing the execution of a resource directory.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
