title: <p align="center"> Derek Bonilla </p>

logo: "/images/logo.png?raw=true" 

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/derekbonilla/">LinkedIn</a> |
  <a href="https://github.com/derekbonilla">GitHub</a>
  </p>

<p align="justify">
  I am currently enrolled in the Google Data Analytics Certificate program.
  <br><br>
  I am currently a Network Consultant at Unite Us with a focus on updating and maintaining large datasets.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
